# Generated by Django 6.0.5 on 2026-06-03 10:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('diet_type', models.CharField(choices=[('low_cal', 'کم کالری'), ('low_carb', 'کم کربوهیدرات'), ('keto', 'کتوژنیک'), ('vegan', 'وگان'), ('gluten_free', 'بدون گلوتن'), ('diabetic', 'مناسب دیابتی\u200cها'), ('paleo', 'پالئو'), ('mediterranean', 'مدیترانه\u200cای')], max_length=20, verbose_name='نوع رژیم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='کلاس آیکون Font Awesome', max_length=50)),
            ],
            options={
                'verbose_name': 'دسته غذایی',
                'verbose_name_plural': 'دسته\u200cهای غذایی',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام غذا')),
                ('meal_type', models.CharField(choices=[('breakfast', '🍳 صبحانه'), ('lunch', '🍱 ناهار'), ('dinner', '🍽️ شام'), ('snack', '🥨 میان وعده')], default='lunch', max_length=20)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('ingredients', models.TextField(help_text='مواد تشکیل دهنده با جزئیات', verbose_name='مواد اولیه')),
                ('allergens', models.CharField(blank=True, help_text='مواد حساسیت\u200cزا (مثل: شیر، تخم\u200cمرغ، گندم، مغزها)', max_length=300)),
                ('calories', models.IntegerField(help_text='کالری', validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(decimal_places=1, help_text='پروتئین (گرم)', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, help_text='کربوهیدرات (گرم)', max_digits=5)),
                ('fat', models.DecimalField(decimal_places=1, help_text='چربی (گرم)', max_digits=5)),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, help_text='فیبر (گرم)', max_digits=5, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=1, help_text='قند (گرم)', max_digits=5, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=1, help_text='سدیم (میلی\u200cگرم)', max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('preparation_time', models.IntegerField(default=20, help_text='زمان آماده\u200cسازی (دقیقه)')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='تصویر اصلی')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='foods/thumbnails/')),
                ('order_count', models.IntegerField(default=0, help_text='تعداد دفعات سفارش')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.foodcategory')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['-order_count', '-created_at'],
            },
        ),
    ]
