# Generated by Django 4.2.30 on 2026-07-16 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-is_available', '-order_count'], 'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AddField(
            model_name='food',
            name='weight_in_grams',
            field=models.PositiveIntegerField(default=250, help_text='وزن تقریبی پرس (گرم)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(help_text='کالری'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='foods.foodcategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='food',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', '🍳 صبحانه'), ('lunch', '🍱 ناهار'), ('dinner', '🍽️ شام'), ('snack', '🥨 میان وعده')], db_index=True, default='lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_time',
            field=models.PositiveIntegerField(default=20, help_text='زمان آماده\u200cسازی (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
