# Generated by Django 4.2.30 on 2026-07-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_food_name_snapshot_alter_order_created_at_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ تراکنش (تومان)')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد ارجاع زرین\u200cپال')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت')),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='usedcoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usedcoupon',
            name='order',
        ),
        migrations.RemoveField(
            model_name='usedcoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='UsedCoupon',
        ),
    ]
