# Generated by Django 4.2.30 on 2026-07-17 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='احراز هویت شده')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی و تخصص\u200cها')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سابقه کار (سال)')),
                ('instagram_id', models.CharField(blank=True, max_length=100, verbose_name='آیدی اینستاگرام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_datetime', models.DateTimeField(verbose_name='تاریخ و ساعت تمرین')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت زمان (دقیقه)')),
                ('status', models.CharField(choices=[('scheduled', 'رزرو شده'), ('completed', 'انجام شد'), ('cancelled', 'لغو شد')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل تمرین (نام باشگاه یا آنلاین)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainers.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک (مثلاً: مقام اول بادی\u200cبیلدینگ)')),
                ('document_type', models.CharField(choices=[('certificate', 'مدرک مربیگری'), ('award', 'حکم قهرمانی / مدال'), ('identity', 'مدرک هویتی')], max_length=20)),
                ('file', models.FileField(upload_to='trainers/documents/')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اخذ')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trainers.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان برنامه (مثلاً: برنامه حجمی ماه اول)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات متنی مربی')),
                ('handwritten_file', models.FileField(blank=True, null=True, upload_to='plans/handwritten/', verbose_name='فایل دست\u200cنویس')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='شاگرد فعال')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_trainers', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='trainers.trainerprofile')),
            ],
            options={
                'unique_together': {('trainer', 'student')},
            },
        ),
    ]
