# Generated by Django 4.2.30 on 2026-07-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_options_food_weight_in_grams_and_more'),
        ('diet_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealplan',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_meals', to='foods.food'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
